style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/odise/terraform-aws-ec2-instance
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
