---
name: misspell
on:
  push:
    branches:
      - master

jobs:
  misspell:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-check
          filter_mode: nofilter
          level: error